### ISSUE TITLE
zip dataset deleted when running IPO

### ISSUE THREAD

**Issue by eschen42** [workflow4metabolomics/ipo#18]
I installed IPO (revision 7) from the test toolshed.

- When I run ipo4xcmsSet, my zip file dataset that I uploaded is deleted.
- Thus, I have to re-upload my zip-file dataset after each time I run ipo4xcmsSet
- When I run ipo4xcmsSet on a single mzML file dataset, the dataset is **not** deleted

**Comment by lecorguille** [comment]
Oh, I see!
I delete the zipfile symlink because it's not well managed by IPO.

Oh, I see!
I did in the right way for [ipo4retgroup.r](https://github.com/workflow4metabolomics/ipo/blob/master/galaxy/ipo/ipo4retgroup.r#L125) but I omitted the `basename` for [ipo4xcmsSet.r](https://github.com/workflow4metabolomics/ipo/blob/master/galaxy/ipo/ipo4xcmsSet.r#L124)

@RJMW Ralf, thanks you for having trying to solve this issue. I will look at your PR.

**Comment by lecorguille** [comment]
I have just merged @RJMW PR and push in the two ToolShed

@eschen42 Thanks for using our wrapper IPO
Don't hesitate to send my your feedbacks about this tool.
